### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Pascal13190** [strangerstudios/pmpro-subscription-delays#30]
Hello,how can I translate this kind of text in French

![image](https://user-images.githubusercontent.com/25581012/119221779-342a3c80-baf1-11eb-92e1-c7e00bd6fa3e.png)

I didn't find then in the po file.

Regards

**Comment by michaelbeil** [comment]
A user sent in a ticket about this in email support (ID 28510)

> I would like know how could I translate Subscription Delay Add-on message in french.
> My website is entirely in french, and with this add-on I have some parts of the website in english.

I let them know that our developers will look into it, but no ETA if/when it will be addressed.
